name: Deploy Infrastructure

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  tf_fmt:
    name: Deploy k8s sandbox cluster
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
    - run: terraform --version
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      working-directory: sandbox-aks
      shell: bash

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan
      env:
        ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      working-directory: sandbox-aks # Use your environment folder
      shell: bash     

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -input=false tf.plan
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} 
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: "[Your Subscription ID]"
        ARM_TENANT_ID: "[Your Tenant ID]"
      working-directory: sandbox-aks # Use your environment folder
      shell: bash

