name: Deploy Infrastructure

# on:
#   pull_request:
#     branches:
#       - main

on:
  push

jobs:
  tf_fmt:
    name: Deploy k8s sandbox cluster
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
    - run: terraform --version
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      working-directory: sandbox-aks
      shell: bash

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan
      env:
        CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      working-directory: sandbox-aks # Use your environment folder
      shell: bash     

