name: Deploy Infrastructure

# on:
#   pull_request:
#     branches:
#       - main

on:
  push

jobs:
  tf_fmt:
    name: Deploy k8s sandbox cluster
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
    - run: terraform --version

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'sandbox-aks'
        CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: 'sandbox-aks'
        CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
        SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
        CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"

